# -*- coding: utf-8 -*-
"""Exercise 4 (BONUS) · Semantic Gate — test runner (TA-provided).

流程 (不需要 pybullet, 不需要 triple store):
    1. 數值/感知層: 把測試場景的事實 grounding 成
       exercises/output/ex4_scene.ttl (graspable / reachable — 只有事實,
       沒有任何 ExecutableGraspTarget 的 assert)。
    2. 語意層: Java SemanticReasoner 載入
       hw3-ontology.ttl + 你的 ex4-semantic-gate.ttl + 場景圖,
       OWL 推理後直接執行 ex4_executable_targets.rq (semantic-gate mode)。
    3. 決策層: 推理導出的 ExecutableGraspTarget 集合 → ALLOW,
       其餘 → REFUSE, 並印出可解釋的理由。

Run:
    python semantic/exercises/ex4_semantic_gate.py
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SEMANTIC = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, 'output')

ONTOLOGY = os.path.join(SEMANTIC, 'ontology', 'hw3-ontology.ttl')
GATE_TTL = os.path.join(HERE, 'ex4-semantic-gate.ttl')
QUERY_RQ = os.path.join(HERE, 'ex4_executable_targets.rq')
SCENE_TTL = os.path.join(OUT_DIR, 'ex4_scene.ttl')
INFERRED = os.path.join(OUT_DIR, 'ex4_inferred.ttl')

JAVA_DIR = os.path.join(SEMANTIC, 'java_semantic_engine')
JAVA_SRC = os.path.join(JAVA_DIR, 'src', 'main', 'java',
                        'course', 'taica', 'hw3', 'SemanticReasoner.java')
JAVA_CLASSES = os.path.join(JAVA_DIR, 'target', 'classes')

EX_NS = 'http://taica.course/hw3/data/ex4#'

# 測試場景 (數值/感知層事實): graspable 是感知層知識, reachable 是 IK 層結果。
# 三個物件恰好覆蓋 ALLOW 與兩個排除方向。
SCENE = [
    {'id': 'objectA', 'label': 'Object A (block on the table)',
     'graspable': True, 'reachable': True},
    {'id': 'objectB', 'label': 'Object B (fixed fixture)',
     'graspable': False, 'reachable': True},
    {'id': 'objectC', 'label': 'Object C (block out of reach)',
     'graspable': True, 'reachable': False},
]


def find_jena():
    for cand in [os.environ.get('JENA_HOME', ''),
                 os.path.join(SEMANTIC, '.cache', 'apache-jena-4.10.0')]:
        if cand and os.path.isdir(os.path.join(cand, 'lib')):
            return cand
    sys.exit("ERROR: Apache Jena not found — run 'bash semantic/run_task4.sh' once first.")


def write_scene():
    lines = [
        '@prefix hw3:  <http://taica.course/hw3/ontology#> .',
        '@prefix ex:   <{}> .'.format(EX_NS),
        '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .',
        '@prefix owl:  <http://www.w3.org/2002/07/owl#> .',
        '',
        '# Auto-generated by ex4_semantic_gate.py — scene facts only',
        '# (ExecutableGraspTarget is NEVER asserted here — your rule derives it)',
        '',
    ]
    for obj in SCENE:
        type_str = 'hw3:GraspableObject' if obj['graspable'] else 'owl:Thing'
        lines += [
            'ex:{} a {} ;'.format(obj['id'], type_str),
            '    rdfs:label "{}" ;'.format(obj['label']),
            '    hw3:isKinematicallyReachable {} .'.format(
                'true' if obj['reachable'] else 'false'),
            '',
        ]
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(SCENE_TTL, 'w') as f:
        f.write('\n'.join(lines))


def run_reasoner(jena_home):
    lib_cp = os.path.join(jena_home, 'lib', '*')
    class_file = os.path.join(JAVA_CLASSES, 'course', 'taica', 'hw3',
                              'SemanticReasoner.class')
    if (not os.path.exists(class_file)
            or os.path.getmtime(JAVA_SRC) > os.path.getmtime(class_file)):
        os.makedirs(JAVA_CLASSES, exist_ok=True)
        subprocess.check_call(['javac', '-cp', lib_cp, '-d', JAVA_CLASSES, JAVA_SRC])

    cp = os.pathsep.join([JAVA_CLASSES, lib_cp])
    out = subprocess.run(
        ['java', '-cp', cp, 'course.taica.hw3.SemanticReasoner',
         INFERRED, QUERY_RQ, ONTOLOGY, GATE_TTL, SCENE_TTL],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        universal_newlines=True)
    if out.returncode != 0:
        print(out.stdout)
        print(out.stderr)
        sys.exit('ERROR: SemanticReasoner failed — check ex4-semantic-gate.ttl syntax.')
    executable = set()
    for line in out.stdout.splitlines():
        if line.startswith('RESULT|'):
            uri = line.split('|')[1]
            if uri:
                executable.add(uri.split('#')[-1])
    return executable


def main():
    print('Exercise 4 (BONUS) · Semantic Gate — decision reasoning')
    print()

    write_scene()
    executable = run_reasoner(find_jena())

    expected = {o['id'] for o in SCENE if o['graspable'] and o['reachable']}

    print('  inferred hw3:ExecutableGraspTarget = {}'.format(sorted(executable)))
    print()
    for obj in SCENE:
        allowed = obj['id'] in executable
        verdict = 'ALLOW ' if allowed else 'REFUSE'
        if allowed:
            why = 'graspable ∧ reachable — derived by YOUR reasoning rule'
        elif not obj['graspable']:
            why = 'reachable BUT NOT GraspableObject (semantic exclusion)'
        elif not obj['reachable']:
            why = 'graspable BUT NOT reachable (geometric exclusion)'
        else:
            why = ('both conditions hold but the class was not derived — '
                   'complete the STUDENT TODO in ex4-semantic-gate.ttl')
        print('  [{}] ex:{:<8s} — {}'.format(verdict, obj['id'], why))

    print()
    if executable == expected:
        print('  [PASS] your rule derived exactly the expected targets: {}'
              .format(sorted(expected)))
        sys.exit(0)
    print('  [FAIL] expected {}, got {} — complete the STUDENT TODO in '
          'ex4-semantic-gate.ttl'.format(sorted(expected), sorted(executable)))
    sys.exit(1)


if __name__ == '__main__':
    main()
